Improve test file size version
The longer versions cause pandoc called from rmarkdown to fail with
the following error message:
Error: pandoc document conversion failed with error 1033